
export const Auth = {
  UPDATE_LOCATION: 'Auth/UPDATE_LOCATION',
  SET_DEVICE_UID: 'Auth/SET_DEVICE_UID'
};

export const Post = {
  FETCH_BEGIN: 'Post/FETCH_BEGIN',
  FETCH_SUCCESS: 'Post/FETCH_SUCCESS',
  FETCH_FAILURE: 'Post/FETCH_FAILURE',
  UPVOTE_BEGIN: 'Post/UPVOTE',
  UPVOTE_SUCCESS: 'Post/UPVOTE_SUCCESS',
  UPVOTE_FAILURE: 'Post/UPVOTE_FAILURE',
  DOWNVOTE_BEGIN: 'Post/DOWNVOTE_BEGIN',
  DOWNVOTE_SUCCESS: 'Post/DOWNVOTE_SUCCESS',
  DOWNVOTE_FAILURE: 'Post/DOWNVOTE_FAILURE'
};
