
export const Auth = {
  UPDATE: 'Auth/UPDATE'
};

export const Post = {
  FETCH_BEGIN: 'Post/FETCH_BEGIN',
  FETCH_SUCCESS: 'Post/FETCH_SUCCESS',
  FETCH_FAILURE: 'Post/FETCH_FAILURE',
  UPVOTE_BEGIN: 'Post/UPVOTE',
  UPVOTE_SUCCESS: 'Post/UPVOTE_SUCCESS',
  UPVOTE_FAILURE: 'Post/UPVOTE_FAILURE',
  DOWNVOTE_BEGIN: 'Post/DOWNVOTE_BEGIN',
  DOWNVOTE_SUCCESS: 'Post/DOWNVOTE_SUCCESS',
  DOWNVOTE_FAILURE: 'Post/DOWNVOTE_FAILURE',
  SAVE_BEGIN: 'Post/SAVE_BEGIN',
  SAVE_SUCCESS: 'Post/SAVE_SUCCESS',
  SAVE_FAILURE: 'Post/SAVE_FAILURE'
};
